apiVersion: v2
name: juice-server
version: 1.0.2
type: application
home: https://github.com/Xdevlab/Run
icon: https://raw.githubusercontent.com/Xdevlab/Run/master/assets/Juice.svg
appVersion: 11.8-2023.03.22-1943.050999b5
maintainers:
  - name: Juice Technologies, Inc.
    url: juicelabs.co
