metadata:
  labels:
    app.kubernetes.io/name: juice
    app.kubernetes.io/component: server
spec:
  restartPolicy: Never
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/region
            operator: In
            values:
            - us-west
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
serverContainer:
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "4"
      memory: "16Gi"
      nvidia.com/gpu: "1"
