apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: juicelabs.co/controller/frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: juicelabs.co/controller/frontend
{{- if and .Values.frontend.spec .Values.frontend.spec.additionalSpec }}
{{ toYaml .Values.frontend.spec.additionalSpec | indent 2 }}
{{- end }}
  template:
    metadata:
      labels:
        app: juicelabs.co/controller/frontend
    spec:
{{- if and .Values.frontend.spec .Values.frontend.spec.template .Values.frontend.spec.template.additionalSpec }}
{{ toYaml .Values.frontend.spec.template.additionalSpec | indent 6 }}
{{- end }}
      containers:
      - name: controller
        image: {{ .Values.image }}
{{- if and .Values.frontend.spec .Values.frontend.spec.template .Values.frontend.spec.template.controller .Values.frontend.spec.template.controller.additionalSpec }}
{{ toYaml .Values.frontend.spec.template.controller.additionalSpec | indent 8 }}
{{- end }}