apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
{{- if or .Values.frontend.additionalAnnotations (and .Values.common .Values.common.additionalAnnotations) }}
  annotations:
{{- if and .Values.common .Values.common.additionalAnnotations }}
{{ toYaml .Values.common.additionalAnnotations | indent 4 }}
{{- end }}
{{- if .Values.frontend.additionalAnnotations }}
{{ toYaml .Values.frontend.additionalAnnotations | indent 4 }}
{{- end }}
{{- end }}
spec:
  selector:
    app.juicelabs.co/controller: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: controller
{{- if .Values.service.additionalSpec }}
{{ toYaml .Values.service.additionalSpec | indent 2 }}
{{- end}}
