name: Controller Docker Image

on:
  push:
    branches:
    - master

jobs:
  docker:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Determine Controller Version
        env:
          SHA: ${{ github.sha }}
        id: version
        shell: bash
        run: |
          tag=`git show -s --date=format:'%Y.%m.%d-%H%M' --format=%cd.%h ${SHA}`
          echo "::set-output name=version::${tag}"
      - name: Controller Image
        uses: docker/build-push-action@v3
        with:
          context: docker/controller
          push: true
          tags: juicelabs/controller:${{ steps.version.outputs.version }}
