name: Docker Images

on:
  release:
    types:
    - released

jobs:
  docker:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to AWS ECR
        uses: docker/login-action@v2
        with:
          registry: 597595123756.dkr.ecr.us-east-2.amazonaws.com
          username: ${{ secrets.AWS_ECR_USERNAME }}
          password: ${{ secrets.AWS_ECR_TOKEN }}
      - name: Client Image
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BASE_CONTAINER=ubuntu:20.04
            JUICE_VERSION=${{ github.ref_name }}
          context: docker/client
          push: true
          tags: juicelabs/client:${{ github.ref_name }}
      - name: Server Image
        uses: docker/build-push-action@v3
        with:
          build-args: |
            BASE_CONTAINER=nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu20.04
            JUICE_VERSION=${{ github.ref_name }}
          context: docker/server
          push: true
          tags: juicelabs/server:${{ github.ref_name }}
