name: Docker Images

on:
  release:
    types: [published]

jobs:
  docker:
    strategy:
      fail-fast: true
      matrix:
        ubuntuos: [18, 20, 22]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Ubuntu ${{ matrix.ubuntuos }}.04
        uses: docker/build-push-action@v3
        with:
          build-arg: |
            BASE_CONTAINER=nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu${{ matrix.ubuntuos }}.04
            OS_NAME=ubuntu-${{ matrix.ubuntuos }}
            JUICE_VERSION=${{ github.ref_name }}
          context: server/ubuntu
          push: true
          tags: juicelabs/server:${{ github.ref_name }}-ubuntu-${{ matrix.ubuntuos }}
